### ISSUE TITLE
Create different mappings for Items and Collections

### ISSUE THREAD

**Issue by quetcodesfire** [stac-utils/stac-api#18]

**Comment by matthewhanson** [comment]
The current mappings are pretty basic, because Elasticsearch does dynamic mapping which makes this not completely necessary.

However, explicit mappings can't hurt and can prevent some errors (such as when the first record ingested is an integer, but subsequent ones are float). But I do not think it is needed at this time, pushing to future.

**Comment by matthewhanson** [comment]
different mappings for collections and items, and dynamic_templates expanded
